In [1]:
import pandas as pd

In [22]:
df=pd.read_csv("lista.csv")
df.head(50)

                         Country ID_Country
0                    Afghanistan        AFG
1                        Albania        ALB
2                        Algeria        DZA
3                         Angola        AGO
4                      Argentina        ARG
5                        Armenia        ARM
6                      Australia        AUS
7                        Austria        AUT
8                     Azerbaijan        AZE
9                        Bahrain        BHR
10                    Bangladesh        BGD
11                       Belarus        BLR
12                       Belgium        BEL
13                         Benin        BEN
14                       Bolivia        BOL
15        Bosnia and Herzegovina        BIH
16                      Botswana        BWA
17                        Brazil        BRA
18                      Bulgaria        BGR
19                  Burkina Faso        BFA
20                       Burundi        BDI
21                      Cambodia        KHM
22                      Cameroon        CMR
23                        Canada        CAN
24      Central African Republic        CAF
25                          Chad        TCD
26                         Chile        CHL
27                         China        CHN
28                      Colombia        COL
29                         Congo        COG
30                    Costa Rica        CRI
31                 Cote d'Ivoire        CIV
32                       Croatia        HRV
33                          Cuba        CUB
34                        Cyprus        CYP
35                       Czechia        CZE
36  Democratic Republic of Congo        COD
37                       Denmark        DNK
38                      Djibouti        DJI
39            Dominican Republic        DOM
40                    East Timor        TLS
41                       Ecuador        ECU
42                         Egypt        EGY
43                   El Salvador        SLV
44             Equatorial Guinea        GNQ
45                       Eritrea        ERI
46                       Estonia        EST
47                      Eswatini        SWZ
48                      Ethiopia        ETH
49                       Finland        FIN

In [24]:
df_c=pd.read_csv("countries-3.csv")
df_c.head(50)

   Continent                           Country ID_Country
0     Africa                           Algeria        DZA
1     Africa                             Egypt        EGY
2     Africa                             Libya        LBY
3     Africa                           Morocco        MAR
4     Africa                             Sudan        SDN
5     Africa                           Tunisia        TUN
6     Africa                    Western Sahara        ESH
7     Africa    British Indian Ocean Territory        IOT
8     Africa                           Burundi        BDI
9     Africa                           Comoros        COM
10    Africa                          Djibouti        DJI
11    Africa                           Eritrea        ERI
12    Africa                          Ethiopia        ETH
13    Africa       French Southern Territories        ATF
14    Africa                             Kenya        KEN
15    Africa                        Madagascar        MDG
16    Africa                            Malawi        MWI
17    Africa                         Mauritius        MUS
18    Africa                           Mayotte        MYT
19    Africa                        Mozambique        MOZ
20    Africa                           Réunion        REU
21    Africa                            Rwanda        RWA
22    Africa                        Seychelles        SYC
23    Africa                           Somalia        SOM
24    Africa                       South Sudan        SSD
25    Africa                            Uganda        UGA
26    Africa       United Republic of Tanzania        TZA
27    Africa                            Zambia        ZMB
28    Africa                          Zimbabwe        ZWE
29    Africa                            Angola        AGO
30    Africa                          Cameroon        CMR
31    Africa          Central African Republic        CAF
32    Africa                              Chad        TCD
33    Africa                             Congo        COG
34    Africa  Democratic Republic of the Congo        COD
35    Africa                 Equatorial Guinea        GNQ
36    Africa                             Gabon        GAB
37    Africa             Sao Tome and Principe        STP
38    Africa                          Botswana        BWA
39    Africa                          Eswatini        SWZ
40    Africa                           Lesotho        LSO
41    Africa                           Namibia        NAM
42    Africa                      South Africa        ZAF
43    Africa                             Benin        BEN
44    Africa                      Burkina Faso        BFA
45    Africa                        Cabo Verde        CPV
46    Africa                     Côte d’Ivoire        CIV
47    Africa                            Gambia        GMB
48    Africa                             Ghana        GHA
49    Africa                            Guinea        GIN

In [28]:
df_m=df.merge(right=df_c,how="left",right_on="ID_Country",left_on="ID_Country")

df_m = df_m.dropna(subset=['ID_Country'])

df_m.head(150)

                Country_x ID_Country Continent             Country_y
0             Afghanistan        AFG      Asia           Afghanistan
1                 Albania        ALB    Europe               Albania
2                 Algeria        DZA    Africa               Algeria
3                  Angola        AGO    Africa                Angola
4               Argentina        ARG  Americas             Argentina
..                    ...        ...       ...                   ...
145                Turkey        TUR      Asia               Türkiye
146          Turkmenistan        TKM      Asia          Turkmenistan
147                Uganda        UGA    Africa                Uganda
148               Ukraine        UKR    Europe               Ukraine
149  United Arab Emirates        ARE      Asia  United Arab Emirates

[150 rows x 4 columns]

In [33]:
##df_m=df.drop(columns=['Country_y'])
##df_m.head(150)
df_m=pd.read_csv("lista_m.csv",
                    header=0,
                    ##sep=",",
                    usecols=[2,0,1],
                    names=["Country","ID_Country","Continent"]
                  )
##df_csv.insert(0, 'Country_ID', range(1, len(df_csv) + 1))
df_m.head(15)

        Country ID_Country Continent
0   Afghanistan        AFG      Asia
1       Albania        ALB    Europe
2       Algeria        DZA    Africa
3        Angola        AGO    Africa
4     Argentina        ARG  Americas
5       Armenia        ARM      Asia
6     Australia        AUS   Oceania
7       Austria        AUT    Europe
8    Azerbaijan        AZE      Asia
9       Bahrain        BHR      Asia
10   Bangladesh        BGD      Asia
11      Belarus        BLR    Europe
12      Belgium        BEL    Europe
13        Benin        BEN    Africa
14      Bolivia        BOL  Americas

In [34]:
df_m.to_csv('countries_c.csv', index=False)

In [12]:
df.merge.head(50)

AttributeError: 'function' object has no attribute 'head'